language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=YAJSONObject/YAJSONObject.xcodeproj
  - IOS_FRAMEWORK_SCHEME="YAJSONObject"
  - IOS_SDK=iphonesimulator9.2
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"      SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"
    - DESTINATION="OS=8.2,name=iPhone 5"       SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"
    - DESTINATION="OS=8.3,name=iPhone 5S"      SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"
    - DESTINATION="OS=8.4,name=iPhone 6"       SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"  SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"
    - DESTINATION="OS=9.1,name=iPhone 6S"      SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"
    - DESTINATION="OS=9.2,name=iPhone 6S Plus" SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
notifications:
  slack:
    secure: TOeLLBBEdu2Zll3fPnVpbAB4o3wTVvR6ccsdiip4HqxxSrK16550pASGEUuTzgkfpGaQbD03Ngk4hZLx2poIxSVUsw5Yewfcn1/YlcgTdwLm1QFkKRDvslulhLCz2CCBigsdInhFkjBbqSgxaDHxUcQ2Auttteq1lkjT46tPUPhMi/jwu/FNA/uTYDvKreNdq4suXc2EQKMLe/pgqWZmqJQMyohGcMjxFKP2+coQYyGS/ibz82YgzTcmez/7nx89lGmBUedF6WCccVLR9Pb9tEA2jnocgxGAAna6xoHkQIS2+X7yYP5kuZMgxkXmot2gAFIfocbKBxGh6/85b81M43Ge/0jKgdYaoPHXXnHkolVdt43RYe6ZZrvg3JSSEnX28PWU8YNqDL5RuXO7K9i5+HMtOjPQoZCq0JXtuEuvURcEZVMk5bIk+BQixWK1X0Wz58Xj5TT6H78I6IC6jWVGHHHsFS8mjUFfAQyC4VTbsbpy3MA+so9iU0R5lv5dUDQf6aZcdZb61+9iMUuffd8LFO9I3zGEDi1RHx3MFfTeGkYaXnl4YhFVC4Si1IuYagV8n9/CcwbjWoReOi82fpfL5RQU2YkKY4S2RrE0ilUeF8ppr+D0tP5aUBvMtZVNwDQwILzkGwYupnebqYUKstpK5mec5XI55aAXOSxv8giV+uc=
